
experiments:
  short_baseline:
    run: true
    model: "ShortBaselineModel"
    lr: 0.001
    weight_decay: 0.0  
    epochs: 5
    log_dir: "runs/exp_001_vanila_short_baseline"

  deep_baseline:
    run: true
    model: "DeepBaselineModel"
    lr: 0.0001
    weight_decay: 0.0  
    epochs: 10
    log_dir: "runs/exp_002_vanila_deep_baseline"


  batch_deep_baseline:
    run: false
    model: "BatchDeepBaselineModel"
    lr: 0.0003
    weight_decay: 0.0
    epochs: 20
    log_dir: "runs/exp_003_upgrade_batch_deep_baseline"

    residual_deep_baseline:
    run: false
    model: "ResidualDeepBaselineModel"
    lr: 0.0003
    weight_decay: 0.0
    epochs: 20
    log_dir: "runs/exp_004_upgrade_residual_deep_baseline"